DROP TABLE IF EXISTS Pages CASCADE
CREATE TABLE Pages(id INTEGER PRIMARY KEY, url TEXT NOT NULL, is_scraping BOOLEAN, created_at TIMESTAMP WITHOUT TIME ZONE,updated_at TIMESTAMP WITHOUT TIME ZONE);
DROP TABLE IF EXISTS Links
CREATE TABLE Links(id INTEGER PRIMARY KEY, page_id INTEGER, url TEXT NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE, FOREIGN KEY (page_id) REFERENCES Pages(id));